version: "3.8"

networks:
  avail_network:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: postgres
    networks:
      - avail_network
    environment:
      POSTGRES_DB: squid_avail_turing
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
    volumes:
     - avail-data:/var/lib/postgresql/data
    restart: unless-stopped
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: avail-squid
    networks:
      - avail_network
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    command: ["sqd", "process"]
    env_file:
      - .env
    depends_on: 
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
    restart: unless-stopped
volumes:
  avail-data:
