version: "3.7"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid_avail
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
    volumes:
     - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped
    
  app:
    image: avail-squid:v1
    working_dir: /app
    ports:
      - "3000:3000"
    command: ["sqd", "process"]
    env_file:
      - .env
    depends_on: 
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
    
    restart: unless-stopped
